using System;
using System.Collections.Generic;

namespace MMR.Randomizer.Constants
{
    // Alignment is intentional, please don't remove it, it's easier to read and multi-line edit

    public static class AudioSequenceIds {
        /// <summary>
        /// Stores sequence ID magic numbers to named constant values and a dictionary of sequence that can be used as song slots.
        /// </summary>
        public enum Id: int
        {
            MASTER_SEQUENCE             = 0x00,
            NATURE_AMBIENCE             = 0x01,
            TERMINA_FIELD               = 0x02,
            PURSUIT_THEME               = 0x03,
            MAJORAS_THEME               = 0x04,
            CLOCK_TOWER_INTERIOR        = 0x05,
            STONE_TOWER                 = 0x06,
            INVERTED_STONE_TOWER        = 0x07,
            EVENT_FAIL_1                = 0x08,
            EVENT_FAIL_2                = 0x09,
            HAPPY_MASK_THEME            = 0x0A,
            SONG_OF_HEALING_THEME       = 0x0B,
            SOUTHERN_SWAMP              = 0x0C,
            ALIENS_THEME                = 0x0D,
            BOAT_CRUISE                 = 0x0E,
            SHARPS_CURSE                = 0x0F,
            GREAT_BAY_COAST             = 0x10,
            IKANA_CANYON                = 0x11,
            DEKU_PALACE                 = 0x12,
            SNOWHEAD_MOUNTAINS          = 0x13,
            PIRATES_FORTRESS            = 0x14,
            CLOCK_TOWN_1                = 0x15,
            CLOCK_TOWN_2                = 0x16,
            CLOCK_TOWN_3                = 0x17,
            FILE_SELECT                 = 0x18,
            EVENT_SUCCESS               = 0x19,
            SMALL_ENEMY_BATTLE          = 0x1A,
            BOSS_ENEMY_BATTLE           = 0x1B,
            WOODFALL_TEMPLE             = 0x1C,
            MORNING_THEME               = 0x1D,
            INTRO_CUTSCENE_1            = 0x1E,
            HOUSE_THEME                 = 0x1F,
            GAME_OVER                   = 0x20,
            BOSS_DEFEATED               = 0x21,
            ITEM_GET                    = 0x22,
            POINTER_0x16                = 0x23,
            HEART_CONTAINER_GET         = 0x24,
            MINIGAME_THEME              = 0x25,
            GORON_RACE                  = 0x26,
            MUSIC_BOX_HOUSE             = 0x27,
            POINTER_0x18                = 0x28,
            ZELDAS_THEME                = 0x29,
            ROSA_SISTERS_THEME          = 0x2A,
            OPEN_CHEST                  = 0x2B,
            CURIOSITY_SHOP_AND_LAB      = 0x2C,
            GIANTS_THEME                = 0x2D,
            GURU_GURUS_THEME            = 0x2E,
            ROMANI_RANCH                = 0x2F,
            GORON_SHRINE                = 0x30,
            MAYORS_OFFICE               = 0x31,
            EPONAS_SONG                 = 0x32,
            SUNS_SONG                   = 0x33,
            SONG_OF_TIME                = 0x34,
            SONG_OF_STORMS              = 0x35,
            ZORA_HALL                   = 0x36,
            MASK_GET                    = 0x37,
            BIG_ENEMY_BATTLE            = 0x38,
            HEART_PIECE_GET             = 0x39,
            ASTRAL_OBSERVATORY          = 0x3A,
            SECRET_GROTTO               = 0x3B,
            MILK_BAR                    = 0x3C,
            TRUTH_REVEALED              = 0x3D,
            WOODS_OF_MYSTERY            = 0x3E,
            GORON_RACE_WIN              = 0x3F,
            HORSE_RACE                  = 0x40,
            HORSE_RACE_WIN              = 0x41,
            GORMAN_BROS_THEME           = 0x42,
            WITCHES_THEME               = 0x43,
            ITEM_SHOP                   = 0x44,
            OWLS_THEME                  = 0x45,
            MINIGAME_SHOP               = 0x46,
            SONG_OF_SOARING             = 0x47,
            SONG_OF_HEALING             = 0x48,
            INVERTED_SONG_OF_TIME       = 0x49,
            SONG_OF_DOUBLE_TIME         = 0x4A,
            SONATA_OF_AWAKNING_THEME    = 0x4B,
            GORON_LULLABY_THEME         = 0x4C,
            NEW_WAVE_BOSSA_NOVA_THEME_1 = 0x4D,
            ELEGY_OF_EMPTINESS_THEME    = 0x4E,
            OATH_TO_ORDER_THEME         = 0x4F,
            SWORDSMANS_SCHOOL           = 0x50,
            LULLABY_INTRO               = 0x51,
            SONG_GET                    = 0x52,
            BREMEN_MARCH                = 0x53,
            BALLAD_OF_THE_WIND_FISH     = 0x54,
            SOARING_THEME               = 0x55,
            POINTER_0x3C                = 0x56,
            FINAL_HOURS                 = 0x57,
            MIKAUS_PLEA_LOOP            = 0x58,
            MIKAUS_PLEA_END             = 0x59,
            DON_GEROS_THEME             = 0x5A,
            SONATA_OF_AWAKENING         = 0x5B,
            GORON_LULLABY               = 0x5C,
            NEW_WAVE_BOSSA_NOVA         = 0x5D,
            ELEGY_OF_EMPTINESS          = 0x5E,
            OATH_TO_ORDER               = 0x5F,
            POINTER_0x57                = 0x60,
            POINTER_0x51                = 0x61,
            JAPAS_JAM_SESSION           = 0x62,
            EVANS_PIANO_SOLO            = 0x63,
            INDIGO_GOS_REHEARSAL        = 0x64,
            SNOWHEAD_TEMPLE             = 0x65,
            GREAT_BAY_TEMPLE            = 0x66,
            NEW_WAVE_BOSSA_NOVA_THEME_2 = 0x67,
            NEW_WAVE_BOSSA_NOVA_THEME_3 = 0x68,
            MAJORAS_WRATH_BATTLE        = 0x69,
            MAJORAS_INCARNATION_BATTLE  = 0x6A,
            MAJORAS_MASK_BATTLE         = 0x6B,
            JAPAS_ROOM                  = 0x6C,
            TIJOS_ROOM                  = 0x6D,
            EVANS_ROOM                  = 0x6E,
            IKANA_CASTLE                = 0x6F,
            GIANTS_APPEAR               = 0x70,
            KAMAROS_THEME               = 0x71,
            CREMIAS_THEME               = 0x72,
            KEATONS_THEME               = 0x73,
            END_CREDITS_1               = 0x74,
            INTRO_CUTSCENE_2            = 0x75,
            TITLE_DEMO                  = 0x76,
            TEMPLE_APPEARS              = 0x77,
            TEMPLE_CLEAR_SHORT          = 0x78,
            TEMPLE_CLEAR_LONG           = 0x79,
            SILENCE                     = 0x7A,
            MOON_ENRAGED                = 0x7B,
            GIANTS_LEAVE                = 0x7C,
            REUNION_THEME               = 0x7D,
            MOON_DESTROYED              = 0x7E,
            END_CREDITS_2               = 0x7F,
        }

        // Store the sequences that can currently be randomized, their internal name, their display name, and their type
        // This is used during SEQS plaintext to YAML conversion, as well as ensuring the sequence ID from a SEQS file
        // matches a vanilla ID if it's an available vanilla sequence slot
        /// <summary>
        /// A dictionary of sequence IDs that can be used as song slots and a tuple for its internal name, display name, and song type.
        /// </summary>
        public static readonly Dictionary<Id, (string Name, string DisplayName, string Type)> SEQUENCE_ID_MAP = new()
        {
            { Id.TERMINA_FIELD,              ("mm-terminafield",               "Termina Field",               "bgm") },
            { Id.SNOWHEAD_MOUNTAINS,         ("mm-snowheadmountains",          "Snowhead",                    "bgm") },
            { Id.GREAT_BAY_COAST,            ("mm-greatbaycoast",              "Great Bay Coast",             "bgm") },
            { Id.IKANA_CANYON,               ("mm-ikanacanyon",                "Ikana Canyon",                "bgm") },
            { Id.SOUTHERN_SWAMP,             ("mm-southernswamp",              "Southern Swamp",              "bgm") },
            { Id.CLOCK_TOWN_1,               ("mm-clocktown1",                 "Clock Town (Day 1)",          "bgm") },
            { Id.CLOCK_TOWN_2,               ("mm-clocktown2",                 "Clock Town (Day 2)",          "bgm") },
            { Id.CLOCK_TOWN_3,               ("mm-clocktown3",                 "Clock Town (Day 3)",          "bgm") },
            { Id.GORON_SHRINE,               ("mm-goronshrine",                "Goron Shrine",                "bgm") },
            { Id.ROMANI_RANCH,               ("mm-romaniranch",                "Romani Ranch",                "bgm") },
            { Id.ZORA_HALL,                  ("mm-zorahall",                   "Zora Hall",                   "bgm") },
            { Id.DEKU_PALACE,                ("mm-dekupalace",                 "Deku Palace",                 "bgm") },
            { Id.SECRET_GROTTO,              ("mm-caves",                      "Secret Grotto",               "bgm") },
            { Id.SNOWHEAD_TEMPLE,            ("mm-snowheadtemple",             "Snowhead Temple",             "bgm") },
            { Id.GREAT_BAY_TEMPLE,           ("mm-greatbaytemple",             "Great Bay Temple",            "bgm") },
            { Id.PIRATES_FORTRESS,           ("mm-piratesfortress",            "Pirates' Fortress",           "bgm") },
            { Id.IKANA_CASTLE,               ("mm-ikanacastle",                "Ancient Castle of Ikana",     "bgm") },
            { Id.STONE_TOWER,                ("mm-stonetower",                 "Stone Tower Temple",          "bgm") },
            { Id.INVERTED_STONE_TOWER,       ("mm-invertedstonetower",         "Inverted Stone Tower Temple", "bgm") },
            { Id.WOODFALL_TEMPLE,            ("mm-woodfalltemple",             "Woodfall Temple",             "bgm") },
            { Id.CLOCK_TOWER_INTERIOR,       ("mm-clocktower",                 "Clock Tower Interior",        "bgm") },
            { Id.GURU_GURUS_THEME,           ("mm-guruguru",                   "Guru-Guru's Theme",           "bgm") },
            { Id.MILK_BAR,                   ("mm-milkbar",                    "Milk Bar",                    "bgm") },
            { Id.HOUSE_THEME,                ("mm-house",                      "House",                       "bgm") },
            { Id.ITEM_SHOP,                  ("mm-shop",                       "Item Shop",                   "bgm") },
            { Id.MINIGAME_SHOP,              ("mm-shootinggallery",            "Minigame Shop",               "bgm") },
            { Id.CURIOSITY_SHOP_AND_LAB,     ("mm-laboratory",                 "Curiosity Shop",              "bgm") },
            { Id.ASTRAL_OBSERVATORY,         ("mm-observatory",                "Astral Observatory",          "bgm") },
            { Id.MUSIC_BOX_HOUSE,            ("mm-musicbox",                   "Music-Box House",             "bgm") },
            { Id.GORON_RACE,                 ("mm-goronrace",                  "Goron Race",                  "bgm") },
            { Id.MINIGAME_THEME,             ("mm-minigame",                   "Minigame",                    "bgm") },
            { Id.CREMIAS_THEME,              ("mm-wagonride",                  "Cremia's Theme",              "bgm") },
            { Id.BOAT_CRUISE,                ("mm-boatcruise",                 "Old Koume's Boat Cruise",     "bgm") },
            { Id.HORSE_RACE,                 ("mm-horserace",                  "Horse Race",                  "bgm") },
            { Id.MAYORS_OFFICE,              ("mm-meeting",                    "Mayor Dotour's Office",       "bgm") },
            { Id.ALIENS_THEME,               ("mm-aliens",                     "Aliens' Theme",               "bgm") },
            { Id.SWORDSMANS_SCHOOL,          ("mm-swordschool",                "Swordsman's School",          "bgm") },
            { Id.SHARPS_CURSE,               ("mm-sharpscurse",                "Sharp's Curse",               "bgm") },
            { Id.PURSUIT_THEME,              ("mm-chase",                      "Pursuit Theme",               "bgm") },
            { Id.MAJORAS_THEME,              ("mm-skullkid",                   "Majora's Theme",              "bgm") },
            { Id.MOON_ENRAGED,               ("mm-maskreveal",                 "The Moon Enraged",            "bgm") },
            { Id.POINTER_0x18,               ("mm-fairyfountain",              "Great Fairy's Fountain",      "bgm") },
            { Id.FILE_SELECT,                ("mm-fileselect",                 "File Select",                 "bgm") },
            { Id.KEATONS_THEME,              ("mm-keaton",                     "Keaton's Theme",              "bgm") },
            { Id.OWLS_THEME,                 ("mm-kaepora",                    "Kaepora Gaebora's Theme",     "bgm") },
            { Id.WITCHES_THEME,              ("mm-witches",                    "Koume & Kotake's Theme",      "bgm") },
            { Id.GORMAN_BROS_THEME,          ("mm-gormanbros",                 "Gorman Bros.' Theme",         "bgm") },
            { Id.WOODS_OF_MYSTERY,           ("mm-mysterywoods",               "Woods of Mystery",            "bgm") },
            { Id.ZELDAS_THEME,               ("mm-zelda",                      "Zelda's Theme",               "bgm") },
            { Id.REUNION_THEME,              ("mm-reunion",                    "Reunion Theme",               "bgm") },
            { Id.SONG_OF_HEALING_THEME,      ("mm-healed",                     "Song of Healing Theme",       "bgm") },
            { Id.GIANTS_THEME,               ("mm-giants",                     "Giants' Theme",               "bgm") },
            { Id.BIG_ENEMY_BATTLE,           ("mm-miniboss",                   "Miniboss Battle",             "bgm") },
            { Id.BOSS_ENEMY_BATTLE,          ("mm-boss",                       "Boss Battle",                 "bgm") },
            { Id.MAJORAS_MASK_BATTLE,        ("mm-mask",                       "Majora's Mask",               "bgm") },
            { Id.MAJORAS_INCARNATION_BATTLE, ("mm-incarnation",                "Majora's Incarnation",        "bgm") },
            { Id.MAJORAS_WRATH_BATTLE,       ("mm-wrath",                      "Majora's Wrath",              "bgm") },
            { Id.EVENT_FAIL_1,               ("mm-f-chasefail",                "Event Failure 1",             "fanfare") },
            { Id.EVENT_FAIL_2,               ("mm-f-fail",                     "Event Failure 2",             "fanfare") },
            { Id.EVENT_SUCCESS,              ("mm-f-clearshort",               "Event Success",               "fanfare") },
            { Id.GAME_OVER,                  ("mm-f-gameover",                 "Game Over",                   "fanfare") },
            { Id.BOSS_DEFEATED,              ("mm-f-bossdown",                 "Boss Defeated",               "fanfare") },
            { Id.ITEM_GET,                   ("mm-f-gotitem",                  "Item Get",                    "fanfare") },
            { Id.HEART_CONTAINER_GET,        ("mm-f-heart",                    "Heart Container Get",         "fanfare") },
            { Id.MASK_GET,                   ("mm-f-mask",                     "Mask Get",                    "fanfare") },
            { Id.HEART_PIECE_GET,            ("mm-f-smallitem",                "Heart Piece Get",             "fanfare") },
            { Id.TRUTH_REVEALED,             ("mm-f-meet",                     "The Truth Revealed",          "fanfare") },
            { Id.GORON_RACE_WIN,             ("mm-f-goronwin",                 "Goron Race Win",              "fanfare") },
            { Id.HORSE_RACE_WIN,             ("mm-f-horsewin",                 "Horse Race Win",              "fanfare") },
            { Id.SONG_GET,                   ("mm-f-song",                     "Song Get",                    "fanfare") },
            { Id.SOARING_THEME,              ("mm-f-soar",                     "Song of Soaring Theme",       "fanfare") },
            { Id.TEMPLE_APPEARS,             ("mm-f-dungeonopen",              "Temple Appears",              "fanfare") },
            { Id.TEMPLE_CLEAR_SHORT,         ("mm-f-dungeonclearshort",        "Temple Clear (Short)",        "fanfare") },
            { Id.TEMPLE_CLEAR_LONG,          ("mm-f-dungeonclearlong",         "Temple Clear (Long)",         "fanfare") },
            { Id.MOON_DESTROYED,             ("mm-f-moonclear",                "The Moon Destroyed",          "fanfare") },
            { Id.GIANTS_LEAVE,               ("mm-f-giantsleave",              "The Giants Farewell",         "fanfare") },
            { Id.KAMAROS_THEME,              ("mm-kamaros-mask-item-dance",    "Kamaro's Theme",              "bgm") },
            { Id.GIANTS_APPEAR,              ("mm-c-giantscs",                 "The Giants Appear",           "bgm") },
            { Id.TITLE_DEMO,                 ("mm-c-titlescreen",              "Title Screen",                "bgm") },
            { Id.SMALL_ENEMY_BATTLE,         ("mm-combat",                     "Enemy Battle",                "bgm") },
            { Id.JAPAS_ROOM,                 ("mm-japas-basspractice",         "Japas' Room",                 "bgm") },
            { Id.TIJOS_ROOM,                 ("mm-tijo-drumpractice",          "Tijo's Room",                 "bgm") },
            { Id.EVANS_ROOM,                 ("mm-evan-pianopractice",         "Evan's Room",                 "bgm") },
            { Id.FINAL_HOURS,                ("mm-finalhours",                 "Final Hours",                 "bgm") },
            { Id.OPEN_CHEST,                 ("mm-opening-a-chest",            "Opening Chest",               "fanfare") },
            { Id.ROSA_SISTERS_THEME,         ("mm-kamaros-dance-rosa-sisters", "Rosa Sisters' Theme",         "bgm") },
        };

        public static bool IsValidSequenceId(int seqId)
        {
            return Enum.IsDefined(typeof(Id), seqId) &&
                seqId >= 0x02 && seqId <= 0x7F &&
                SEQUENCE_ID_MAP.ContainsKey((Id)seqId);
        }
    }
}
