name: .NET Desktop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore

    - name: Test
      run: |
        dotnet test MMR.Common.Tests
        dotnet test MMR.Randomizer.Tests
#       dotnet test MMR.Yaz.Tests

    - name: Build UI exe
      run: dotnet publish MMR.UI\MMR.UI.csproj -c Release -o build -r win-x64 --no-self-contained

    - name: Build CLI exe
      run: dotnet publish MMR.CLI\MMR.CLI.csproj -c Release -o build -r win-x64 --no-self-contained

    - name: Create output directory
      run: md build\output

    - name: Set sha-short variable
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV

    - name: Package
      uses: actions/upload-artifact@v3
      with:
        name: MM-Randomizer-dev-${{ env.sha_short }}
        path: build/
